// react-frontend/src/components/form/form.component.js
import React, { Component } from 'react';

export default class FormComponent extends Component {

    render() {

        const { agregarProducto, onChangE, nombre, marca, precioXUnidad, cantidad, accion } = this.props;
    
        return (
            <div className="card mt-2">
                <div className="card-header text-bg-secondary">
                    Información del producto
                </div>
                <div className="card-body">
                    <form className="d-flex" onSubmit={agregarProducto.bind(this)}>
                        <input 
                            className="form-control me-2" 
                            type="text"
                            name="nombre"
                            placeholder="Nombre del producto"
                            onChange={onChangE.bind(this)}
                            value={nombre}
                            required
                        />
                        <input 
                            className="form-control me-2" 
                            type="text" 
                            name="marca"
                            placeholder="Marca del producto"
                            onChange={onChangE.bind(this)}
                            value={marca}
                            required
                        />
                        <input 
                            className="form-control me-2" 
                            type="number" 
                            name="precioXUnidad"
                            placeholder="Precio por unidad" 
                            min="0"
                            onChange={onChangE.bind(this)}
                            value={precioXUnidad}
                            required
                        />
                        <input 
                            className="form-control me-2" 
                            type="number" 
                            name="cantidad"
                            placeholder="Cantidad de unidades" 
                            min="1"
                            onChange={onChangE.bind(this)}
                            value={cantidad}
                            required
                        />
                        <input 
                            type="submit" 
                            className="btn btn-primary" 
                            value={accion}>    
                        </input>
                    </form>
                </div>
            </div>
        )

    }

}

// Angular-Frontend/src/app/components/form/form.component.ts
import { Component, OnInit } from '@angular/core';
import { ProductoService } from 'src/app/services/producto.service';

@Component({
  selector: 'app-form',
  templateUrl: './form.component.html',
  styleUrls: ['./form.component.css']
})
export class FormComponent implements OnInit {

  constructor(public productoService: ProductoService) { }

  ngOnInit(): void {
  }

}

<div class="card mt-2">
    <div class="card-header text-bg-secondary">
        Información del producto
    </div>
    <div class="card-body">
        <form class="d-flex">
            <input 
                class="form-control me-2" 
                type="text"
                name="nombre"
                placeholder="Nombre del producto"
                [(ngModel)] = "productoService.producto.nombre"
                required
            />
            <input 
                class="form-control me-2" 
                type="text" 
                name="marca"
                placeholder="Marca del producto"
                [(ngModel)] = "productoService.producto.marca"
                required
            />
            <input 
                class="form-control me-2" 
                type="number" 
                name="precioXUnidad"
                placeholder="Precio por unidad" 
                min="0"
                [(ngModel)] = "productoService.producto.precioXUnidad"
                required
            />
            <input 
                class="form-control me-2" 
                type="number" 
                name="cantidad"
                placeholder="Cantidad de unidades" 
                min="1"
                [(ngModel)] = "productoService.producto.cantidad"
                required
            />
            <input 
                type="submit" 
                class="btn btn-primary" 
                value="{{ productoService.accion }}"
                (click)="productoService.agregarProducto($event)"
            />
        </form>
    </div>
</div>
