// react-frontend/src/components/nav/nav.component.js
import React, { Component } from 'react';
import './nav.component.css';

export default class NavComponent extends Component {

    state = {
        precio: '0',
        cantidad: '0'
    }

    obtenerTotal(productos) {
        let tot = 0;
        productos.map(p => {
            tot += (p.precioXUnidad * p.cantidad)
        })
        return tot;
    }

    onChangE = e => {
        const estadoActual = e.target.value.split(";")
        this.setState({precio: estadoActual[0],cantidad: estadoActual[1]})
    }

    render() {

        const { productos } = this.props;
    
        return (
            <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
                <div className="container-fluid">
                    <a className="navbar-brand" href="#">
                        <img src="favicon.ico" alt="" />
                        MERN-StockApp
                    </a>
                    <ul className="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li className="nav-item">
                            <a className="nav-link active disabled" href="#">Monto total: {this.obtenerTotal(productos)}</a>
                        </li>
                        <li className="nav-item">
                            <a className="nav-link active disabled" href="#">Productos: {productos.length}</a>
                        </li>
                        <li className="nav-item">
                            <a className="nav-link active" href="#">
                                <select defaultValue={'default'} name="select" onChange={this.onChangE}>
                                    <option value="default" disabled>Producto - Marca</option>
                                    {productos.map(producto => {
                                        return <option key={producto._id} value={producto.precioXUnidad + ";" + producto.cantidad}>{producto.nombre} - {producto.marca}</option>
                                    })}
                                </select>
                            </a>
                        </li>
                        <li className="nav-item">
                            <a className="nav-link active disabled" href="#">
                                <b>Unidades:</b> {this.state.precio}
                            </a>
                        </li>
                        <li className="nav-item">
                            <a className="nav-link active disabled" href="#">
                                <b>Precio:</b> {this.state.cantidad}
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        );
    
    }

}

// Angular-Frontend/src/app/components/nav/nav.component.ts
import { Component, OnInit } from '@angular/core';
import { ProductoService } from 'src/app/services/producto.service';

@Component({
  selector: 'app-nav',
  templateUrl: './nav.component.html',
  styleUrls: ['./nav.component.css']
})
export class NavComponent implements OnInit {

  cantidad = 0;
  precio = 0;

  constructor(public productoService: ProductoService) { }

  ngOnInit(): void {
  }

  obtenerTotal(): number {
    let tot = 0;
    this.productoService.productos.map(p => {
        tot += (p.precioXUnidad * p.cantidad)
    })
    return tot;
  }

  onChangE(e: any) {
    const estadoActual = e.target.value.split(";")
    this.precio = estadoActual[0];
    this.cantidad = estadoActual[1];
  }
}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="../favicon.ico" alt="">
            MEAN-StockApp
        </a>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active disabled" href="#">Monto total: {{ obtenerTotal() }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active disabled" href="#">Productos: {{ productoService.productos.length }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="#">
                    <select name="select" (change)="onChangE($event)">
                        <option selected disabled>Producto - Marca</option>
                        <option *ngFor="let producto of productoService.productos" [value]="producto.precioXUnidad + ';' + producto.cantidad"> {{producto.nombre}} - {{producto.marca}}</option>
                    </select>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link active disabled" href="#">
                    <b>Unidades:</b> {{ precio }}
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link active disabled" href="#">
                    <b>Precio:</b> {{ cantidad }}
                </a>
            </li>
        </ul>
    </div>
</nav>
